services:
  server:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - beyondchats-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - beyondchats-net

networks:
  beyondchats-net:
    external: true
