services:
  server:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    networks:
      - beyondchats-net

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - beyondchats-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - beyondchats-net

volumes:
  mongo_data:

networks:
  beyondchats-net:
    external: true
